version: 2

sources:
  - name: erp_adventureworks
    tables:
      - name: orders
      - name: customers
        columns:
          - name: customerid
            description: Chave primária da tabela Clientes
            tests:
              - unique
              - not_null
      - name: prooducts
        columns:
          - name: productid
            description: Chave primária da tabela Produtos
      - name: order_details
        columns:
          - name: salesorderid
      - name: reasons
        columns:
          - name: salesreasonid
      - name: creditcard
        columns:
          - name: creditcardid
      - name: address
        columns:
          - name: addressid
      - name: stateprovince
        columns:
          - name: stateprovinceid
      - name: countryregion
        columns:
          - name: countryregioncode
      - name: reasonsbridge
        columns:
          - name: salesorderid
      - name: sales_salesorderheader
        columns:
          - name: salesorderid
      - name: personbridge
        columns:
          - name: businessentityid
      - name: person
        columns:
          - name: personid
      - name: businessentitycontact
        columns:
          - name: businessentityid
      - name: store
        columns:
          - name: customerid